// Generated by React Router

import "react-router";

declare module "react-router" {
	interface Register {
		pages: Pages;
		routeFiles: RouteFiles;
		routeModules: RouteModules;
	}
}

type Pages = {
	"/": {
		params: {};
	};
	"/login": {
		params: {};
	};
	"/register": {
		params: {};
	};
	"/:userId/community": {
		params: {
			userId: string;
		};
	};
	"/:userId/addCommunity": {
		params: {
			userId: string;
		};
	};
	"/:userId/community/:communityId": {
		params: {
			userId: string;
			communityId: string;
		};
	};
	"/:userId/community/:communityId/member": {
		params: {
			userId: string;
			communityId: string;
		};
	};
	"/:userId/community/:communityId/settings": {
		params: {
			userId: string;
			communityId: string;
		};
	};
	"/:userId/community/:communityId/addList": {
		params: {
			userId: string;
			communityId: string;
		};
	};
	"/:userId/community/:communityId/:listId": {
		params: {
			userId: string;
			communityId: string;
			listId: string;
		};
	};
	"/:userId/community/:communityId/:listId/:itemId": {
		params: {
			userId: string;
			communityId: string;
			listId: string;
			itemId: string;
		};
	};
	"/:userId/community/:communityId/:listId/:itemId/thread": {
		params: {
			userId: string;
			communityId: string;
			listId: string;
			itemId: string;
		};
	};
	"/:userId/community/:communityId/addItem": {
		params: {
			userId: string;
			communityId: string;
		};
	};
	"/:userId/profile": {
		params: {
			userId: string;
		};
	};
	"/:userId/profile/edit": {
		params: {
			userId: string;
		};
	};
	"/:userId/favorites": {
		params: {
			userId: string;
		};
	};
	"/:userId/notifications": {
		params: {
			userId: string;
		};
	};
};

type RouteFiles = {
	"root.tsx": {
		id: "root";
		page:
			| "/"
			| "/login"
			| "/register"
			| "/:userId/community"
			| "/:userId/addCommunity"
			| "/:userId/community/:communityId"
			| "/:userId/community/:communityId/member"
			| "/:userId/community/:communityId/settings"
			| "/:userId/community/:communityId/addList"
			| "/:userId/community/:communityId/:listId"
			| "/:userId/community/:communityId/:listId/:itemId"
			| "/:userId/community/:communityId/:listId/:itemId/thread"
			| "/:userId/community/:communityId/addItem"
			| "/:userId/profile"
			| "/:userId/profile/edit"
			| "/:userId/favorites"
			| "/:userId/notifications";
	};
	"pages/home.tsx": {
		id: "pages/home";
		page: "/";
	};
	"pages/login.tsx": {
		id: "pages/login";
		page: "/login";
	};
	"pages/register.tsx": {
		id: "pages/register";
		page: "/register";
	};
	"pages/community.tsx": {
		id: "pages/community";
		page: "/:userId/community";
	};
	"pages/addCommunity.tsx": {
		id: "pages/addCommunity";
		page: "/:userId/addCommunity";
	};
	"pages/community/[communityId].tsx": {
		id: "pages/community/[communityId]";
		page: "/:userId/community/:communityId";
	};
	"pages/community/[communityId]/member.tsx": {
		id: "pages/community/[communityId]/member";
		page: "/:userId/community/:communityId/member";
	};
	"pages/community/[communityId]/settings.tsx": {
		id: "pages/community/[communityId]/settings";
		page: "/:userId/community/:communityId/settings";
	};
	"pages/community/[communityId]/addList.tsx": {
		id: "pages/community/[communityId]/addList";
		page: "/:userId/community/:communityId/addList";
	};
	"pages/community/[listId].tsx": {
		id: "pages/community/[listId]";
		page: "/:userId/community/:communityId/:listId";
	};
	"pages/community/[itemId].tsx": {
		id: "pages/community/[itemId]";
		page: "/:userId/community/:communityId/:listId/:itemId";
	};
	"pages/community/[itemId]/thread.tsx": {
		id: "pages/community/[itemId]/thread";
		page: "/:userId/community/:communityId/:listId/:itemId/thread";
	};
	"pages/community/addItem.tsx": {
		id: "pages/community/addItem";
		page: "/:userId/community/:communityId/addItem";
	};
	"pages/profile.tsx": {
		id: "pages/profile";
		page: "/:userId/profile";
	};
	"pages/profile/edit.tsx": {
		id: "pages/profile/edit";
		page: "/:userId/profile/edit";
	};
	"pages/favorites.tsx": {
		id: "pages/favorites";
		page: "/:userId/favorites";
	};
	"pages/notifications.tsx": {
		id: "pages/notifications";
		page: "/:userId/notifications";
	};
};

type RouteModules = {
	root: typeof import("./app/root.tsx");
	"pages/home": typeof import("./app/pages/home.tsx");
	"pages/login": typeof import("./app/pages/login.tsx");
	"pages/register": typeof import("./app/pages/register.tsx");
	"pages/community": typeof import("./app/pages/community.tsx");
	"pages/addCommunity": typeof import("./app/pages/community/addCommunity.js");
	"pages/community/[communityId]": typeof import("./app/pages/community/[communityId].tsx");
	"pages/community/[communityId]/member": typeof import("./app/pages/community/[communityId]/member.tsx");
	"pages/community/[communityId]/settings": typeof import("./app/pages/community/[communityId]/settings.tsx");
	"pages/community/[communityId]/addList": typeof import("./app/pages/community/[communityId]/addList.tsx");
	"pages/community/[listId]": typeof import("./app/pages/community/[listId].tsx");
	"pages/community/[itemId]": typeof import("./app/pages/community/[itemId].tsx");
	"pages/community/[itemId]/thread": typeof import("./app/pages/community/[itemId]/thread.tsx");
	"pages/community/addItem": typeof import("./app/pages/community/addItem.tsx");
	"pages/profile": typeof import("./app/pages/profile.tsx");
	"pages/profile/edit": typeof import("./app/pages/profile/edit.tsx");
	"pages/favorites": typeof import("./app/pages/favorites.tsx");
	"pages/notifications": typeof import("./app/pages/notifications.tsx");
};
