// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/community": {
    params: {};
  };
  "/community/:communityId": {
    params: {
      "communityId": string;
    };
  };
  "/community/:communityId/member": {
    params: {
      "communityId": string;
    };
  };
  "/community/:communityId/settings": {
    params: {
      "communityId": string;
    };
  };
  "/community/:communityId/addList": {
    params: {
      "communityId": string;
    };
  };
  "/community/:communityId/:listId": {
    params: {
      "communityId": string;
      "listId": string;
    };
  };
  "/community/:communityId/:listId/:itemId": {
    params: {
      "communityId": string;
      "listId": string;
      "itemId": string;
    };
  };
  "/community/:communityId/:listId/:itemId/thread": {
    params: {
      "communityId": string;
      "listId": string;
      "itemId": string;
    };
  };
  "/community/:communityId/addItem": {
    params: {
      "communityId": string;
    };
  };
  "/profile": {
    params: {};
  };
  "/profile/edit": {
    params: {};
  };
  "/favorites": {
    params: {};
  };
  "/notifications": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/community" | "/community/:communityId" | "/community/:communityId/member" | "/community/:communityId/settings" | "/community/:communityId/addList" | "/community/:communityId/:listId" | "/community/:communityId/:listId/:itemId" | "/community/:communityId/:listId/:itemId/thread" | "/community/:communityId/addItem" | "/profile" | "/profile/edit" | "/favorites" | "/notifications";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "pages/unauthorized/login.tsx": {
    id: "pages/unauthorized/login";
    page: "/login";
  };
  "pages/unauthorized/register.tsx": {
    id: "pages/unauthorized/register";
    page: "/register";
  };
  "pages/authenticated/_menu.tsx": {
    id: "pages/authenticated/_menu";
    page: "/community" | "/community/:communityId" | "/community/:communityId/member" | "/community/:communityId/settings" | "/community/:communityId/addList" | "/community/:communityId/:listId" | "/community/:communityId/:listId/:itemId" | "/community/:communityId/:listId/:itemId/thread" | "/community/:communityId/addItem" | "/profile" | "/profile/edit" | "/favorites" | "/notifications";
  };
  "pages/authenticated/_menu.home.tsx": {
    id: "pages/authenticated/_menu.home";
    page: "/community";
  };
  "pages/authenticated/community/[communityId].tsx": {
    id: "pages/authenticated/community/[communityId]";
    page: "/community/:communityId";
  };
  "pages/authenticated/community/[communityId]/member.tsx": {
    id: "pages/authenticated/community/[communityId]/member";
    page: "/community/:communityId/member";
  };
  "pages/authenticated/community/[communityId]/settings.tsx": {
    id: "pages/authenticated/community/[communityId]/settings";
    page: "/community/:communityId/settings";
  };
  "pages/authenticated/community/[communityId]/addList.tsx": {
    id: "pages/authenticated/community/[communityId]/addList";
    page: "/community/:communityId/addList";
  };
  "pages/authenticated/community/[listId].tsx": {
    id: "pages/authenticated/community/[listId]";
    page: "/community/:communityId/:listId";
  };
  "pages/authenticated/community/[itemId].tsx": {
    id: "pages/authenticated/community/[itemId]";
    page: "/community/:communityId/:listId/:itemId";
  };
  "pages/authenticated/community/[itemId]/thread.tsx": {
    id: "pages/authenticated/community/[itemId]/thread";
    page: "/community/:communityId/:listId/:itemId/thread";
  };
  "pages/authenticated/community/addItem.tsx": {
    id: "pages/authenticated/community/addItem";
    page: "/community/:communityId/addItem";
  };
  "pages/authenticated/profile/profile.tsx": {
    id: "pages/authenticated/profile/profile";
    page: "/profile";
  };
  "pages/authenticated/profile/edit.tsx": {
    id: "pages/authenticated/profile/edit";
    page: "/profile/edit";
  };
  "pages/authenticated/favorites.tsx": {
    id: "pages/authenticated/favorites";
    page: "/favorites";
  };
  "pages/authenticated/notifications.tsx": {
    id: "pages/authenticated/notifications";
    page: "/notifications";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "pages/unauthorized/login": typeof import("./app/pages/unauthorized/login.tsx");
  "pages/unauthorized/register": typeof import("./app/pages/unauthorized/register.tsx");
  "pages/authenticated/_menu": typeof import("./app/pages/authenticated/_menu.tsx");
  "pages/authenticated/_menu.home": typeof import("./app/pages/authenticated/_menu.home.tsx");
  "pages/authenticated/community/[communityId]": typeof import("./app/pages/authenticated/community/[communityId].tsx");
  "pages/authenticated/community/[communityId]/member": typeof import("./app/pages/authenticated/community/[communityId]/member.tsx");
  "pages/authenticated/community/[communityId]/settings": typeof import("./app/pages/authenticated/community/[communityId]/settings.tsx");
  "pages/authenticated/community/[communityId]/addList": typeof import("./app/pages/authenticated/community/[communityId]/addList.tsx");
  "pages/authenticated/community/[listId]": typeof import("./app/pages/authenticated/community/[listId].tsx");
  "pages/authenticated/community/[itemId]": typeof import("./app/pages/authenticated/community/[itemId].tsx");
  "pages/authenticated/community/[itemId]/thread": typeof import("./app/pages/authenticated/community/[itemId]/thread.tsx");
  "pages/authenticated/community/addItem": typeof import("./app/pages/authenticated/community/addItem.tsx");
  "pages/authenticated/profile/profile": typeof import("./app/pages/authenticated/profile/profile.tsx");
  "pages/authenticated/profile/edit": typeof import("./app/pages/authenticated/profile/edit.tsx");
  "pages/authenticated/favorites": typeof import("./app/pages/authenticated/favorites.tsx");
  "pages/authenticated/notifications": typeof import("./app/pages/authenticated/notifications.tsx");
};